name: "PageSpeed Insights"
description: "Run Google PageSpeed Insights"
inputs:
  url:
    description: "URL to analyze"
    required: true
    default: "https://www.magenx.com"
  strategy:
    description: "Strategy: mobile or desktop"
    required: false
    default: "mobile"
runs:
  using: "composite"
  steps:
    - name: Set up Node.js
      id: nodejs
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 #v4.4.0
      with:
        node-version: "20"
    - name: Install dependencies
      id: npm-install
      shell: bash
      run: npm install @googleapis/pagespeedonline
    - name: Run PageSpeed Insights
      id: psi
      shell: bash
      run: node ${{ github.action_path }}/pagespeed.js "${{ inputs.url }}" "${{ inputs.strategy }}"
