name: "Run security scan"
description: "Downloads and setup scanners and runs a scan on the repository."

inputs:
  ecomscan_key:
    description: "Key for Ecomscan"
    required: true

outputs:
  output:
    description: "The output of the eComscan scan"

runs:
  using: "composite"
  steps:
    - name: Download eComscan
      id: ecomscan
      shell: bash
      run: wget https://ecomscan.com/downloads/linux-amd64/ecomscan

    - name: Run eComscan
      id: security-scan
      env:
        ECOMSCAN_KEY: ${{ inputs.ecomscan_key }}
      shell: bash
      run: |
        chmod +x ecomscan
        outputs=$(./ecomscan --no-auto-update --skip-database --skip-dashboard --newonly --state-file ./security_scan_log .)
        echo "output<<EOF" >> $GITHUB_OUTPUT
        echo "$outputs" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
