name: "Create composer cache"
description: "Cache Composer packages"

outputs:
  cache-hit:
    description: "Cache hit or miss variable"
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - name: Configure Composer cache
      id: composer-cache
      shell: bash
      run: |
        echo "composer_cache_dir=$(composer config cache-dir)" >> $GITHUB_OUTPUT
        echo "composer_cache_key=${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}" >> $GITHUB_OUTPUT

    - name: Cache Composer packages
      id: cache
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: ${{ steps.composer-cache.outputs.composer_cache_dir }}
        key: ${{ steps.composer-cache.outputs.composer_cache_key }}
        restore-keys: |
          ${{ runner.os }}-composer-
