name: Magento Build Workflow

on:
  workflow_call:
    secrets:
      COMPOSER_AUTH:
        required: true
    outputs:
      build_artifact:
        description: "Artifact file name"
        value: ${{ jobs.build.outputs.build_artifact }}
      build_artifact_url:
        description: "URL to the build artifact"
        value: ${{ jobs.build.outputs.build_artifact_url }}
      build_run_id:
        description: "ID of the build workflow run"
        value: ${{ jobs.build.outputs.build_run_id }}
      build_run_url:
        description: "URL to the build workflow run"
        value: ${{ jobs.build.outputs.build_run_url }}

jobs:
  build:
    name: Build Magento
    runs-on: ubuntu-latest
    outputs:
      build_artifact: ${{ steps.build_output.outputs.build_artifact }}
      build_artifact_url: ${{ steps.build_output.outputs.build_artifact_url }}
      build_run_url: ${{ steps.build_output.outputs.build_run_url }}
      build_run_id: ${{ steps.build_output.outputs.build_run_id }}

    steps:
      - name: Checkout latest tag
        id: checkout_latest_tag
        uses: actions/checkout@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          ref: main
          fetch-depth: 0
          persist-credentials: false

      - name: Composer install modules and updates
        id: composer_install
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
        run: |
          composer install --no-dev --no-cache --no-interaction --optimize-autoloader --apcu-autoloader

      - name: Run setup di compile
        id: setup_di_compile
        run: bin/magento setup:di:compile -n

      - name: Generate static files
        id: generate_static_content
        run: bin/magento setup:static-content:deploy -f -n

      - name: Debug with custom output
        id: debug
        run: bin/magento

      - name: Set version for complete build
        id: set_build_version
        run: | 
          echo "BUILD_FILE=build_$(date +%Y%m%d_%H%M).tar.gz" >> ${GITHUB_ENV}

      - name: Package build into tar archive
        id: build_tar_archive
        run: | 
          tar --ignore-failed-read --warning=no-file-changed \
            -czf "${{ env.BUILD_FILE }}" \
            --exclude=".git" \
            --exclude=".github" \
            --exclude="app/etc/env.php" \
            --exclude="CHANGELOG*" \
            --exclude="${{ env.BUILD_FILE }}" \
            .

      - name: Upload build artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUILD_FILE }}
          path: ${{ env.BUILD_FILE }}
          
      - name: Find pre-release target PR
        if: ${{ always() }}
        id: find-pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr=$(gh pr list \
            --repo "$GITHUB_REPOSITORY" \
            --state open \
            --label "autorelease: pending" \
            --search "alpha in:title" \
            --json number \
            --limit 1 \
            --jq '.[0].number')
          echo "pr_number=$pr" >> ${GITHUB_OUTPUT}
          
      - name: Construct PR comment
        if: ${{ always() }}
        id: construct_comment
        run: |
          if [ "${{ steps.composer_install.outcome }}" == "failure" ]; then
            COMMENT+="❌ Composer install failed\n"
          else
            COMMENT+="✔ Composer install succeeded\n"
          fi
          if [ "${{ steps.setup_di_compile.outcome }}" == "failure" ]; then
            COMMENT+="❌ Code compilation failed\n"
          else
            COMMENT+="✔ Code compilation succeeded\n"
          fi
          if [ "${{ steps.generate_static_content.outcome }}" == "failure" ]; then
            COMMENT+="❌ Static content deploy failed\n"
          else
            COMMENT+="✔ Static content deploy succeeded\n"
          fi
          if [ "${{ job.status }}" == "success" ]; then
          COMMENT+="\n## Build and artifact details:\n"
          COMMENT+="- **ARTIFACT_ID**: ${{ steps.upload-artifact.outputs.artifact-id }}\n"
          COMMENT+="- **BUILD_RUN_ID**: ${GITHUB_RUN_ID}\n"
          COMMENT+="- **ARTIFACT_FILE**: ${{ env.BUILD_FILE }}\n"
          COMMENT+="- **BUILD_RUN_URL**: https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}\n"
          COMMENT+="- **ARTIFACT_URL**: ${{ steps.upload-artifact.outputs.artifact-url }}\n"
          fi
          echo "COMMENT<<EOF" >> $GITHUB_ENV
          echo -e "$COMMENT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV 

      - name: Add comment to PR
        if: ${{ steps.find-pr.outputs.pr_number != '' && always() }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: | 
          gh pr comment ${{ steps.find-pr.outputs.pr_number }} --repo "${GITHUB_REPOSITORY}" --body "${COMMENT}"

      - name: Set build outputs
        id: build_output
        run: |
          echo "build_artifact_url=${{ steps.upload-artifact.outputs.artifact-url }}" >> ${GITHUB_OUTPUT}
          echo "build_run_url=https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"  >> ${GITHUB_OUTPUT}
          echo "build_artifact=${{ env.BUILD_FILE }}" >> ${GITHUB_OUTPUT}
          echo "build_run_id=${GITHUB_RUN_ID}"  >> ${GITHUB_OUTPUT}
          
