on:
  workflow_call:

jobs:
  composer-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Composer cache
        id: composer-cache
        run: |
          echo "composer_cache_dir=$(composer config cache-dir)" >> $GITHUB_OUTPUT
          echo "composer_cache_key=${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        id: cache
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ${{ steps.composer-cache.outputs.composer_cache_dir }}
          key: ${{ steps.composer-cache.outputs.composer_cache_key }}
          restore-keys: |
            ${{ runner.os }}-composer-
