name: Build and Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**/*.php'
      - '**/*.xml'
      - '**/*.phtml'
      - 'app/design/**'
      - 'app/code/**'
      - 'app/etc/**'
      - 'composer.json'
      - 'composer.lock'
      
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        ref: ${{ github.ref }}
        fetch-depth: 0
        persist-credentials: false
        
    - name: Github Actions workflow identification
      id: github_user
      run: |
         git config --global user.name "Magenx CI/CD"
         git config --global user.email "admin@magenx.com"

    - name: Install modules and updates
      id: composer_install
      env:
        COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
      run: |
        composer install --no-dev --no-cache --no-interaction  --optimize-autoloader --apcu-autoloader

    - name: Run setup:di:compile
      id: setup_di_compile
      if: ${{ success() }}
      run: bin/magento setup:di:compile -n

    - name: Deploy static files
      id: setup_static_content_deploy
      run: bin/magento setup:static-content:deploy -f -n

    - name: Debug with custom output
      id: debug
      run: bin/magento

    - name: Set version for complete build
      id: set_build_version
      if: ${{ success() }}
      run: | 
        echo "BUILD_FILE=build_$(date +%Y%m%d_%H%M).tar.gz" >> ${GITHUB_ENV}

    - name: Package build into tar
      id: build_tar_archive
      if: ${{ success() }}
      run: | 
        tar --ignore-failed-read --warning=no-file-changed \
          -czf "${{ env.BUILD_FILE }}" \
          --exclude=".git" \
          --exclude=".github" \
          --exclude="${{ env.BUILD_FILE }}" \
          .
          
    - name: Release
      id: create_release
      uses: cycjimmy/semantic-release-action@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        semantic_version: 19.0.5
        extra_plugins: |
          @semantic-release/changelog
          @semantic-release/git
          conventional-changelog-conventionalcommits

