name: Composer Modules Check

on:
  pull_request:
    paths:
      - 'composer.json'

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  composer-install-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          fetch-depth: 0

      - name: Checkout base branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          path: base

      - name: Extract require block from base
        id: require_base
        run: |
          jq -r '.require | keys_unsorted[]' base/composer.json | sort > base/require_modules_old.txt
          composer show --working-dir="base/" --locked -N >  base/locked_modules_old.txt

      - name: Validate composer.json from PR
        id: composer-validate
        run: | 
          composer validate --no-check-all --no-check-lock --no-check-publish --no-check-version 

      - name: Extract require block from PR
        id: require_pr
        run: jq -r '.require | keys_unsorted[]' composer.json | sort > require_modules_new.txt

      - name: Find new modules in require block
        id: find-new-modules
        run: |
          comm -13 base/require_modules_old.txt require_modules_new.txt > modules.txt
          if [ ! -s modules.txt ]; then
            echo "No new modules in require block."
          else
            echo "⚠️ New modules in require block:"
            cat modules.txt
            echo "new_modules=true" >> ${GITHUB_OUTPUT}
          fi

      - uses: reviewdog/action-setup@e04ffabe3898a0af8d0fb1af00c188831c4b5893 #v1.3.2
        with:
          reviewdog_version: v0.20.3

      - name: New modules review comment to PR
        id: module-comment-pr
        if: ${{ steps.find-new-modules.outputs.new_modules == 'true' }}
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          MODULES=$(awk '{printf "[%s] ", $0}' modules.txt | sed 's/ $//')
          printf "composer.json: New modules require: %s\n" "$MODULES" \
          | reviewdog -efm="%f: %m" \
            -name="COMPOSER MODULES REQUIRE" \
            -reporter=github-pr-review \
            -filter-mode=nofilter \
            -level=warning

      - name: Install dependencies
        id: composer-install
        if: ${{ steps.find-new-modules.outputs.new_modules == 'true' }}
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
        run: |
          while read module; do
            composer require "$module"
          done < modules.txt
          composer install --no-interaction --no-dev --no-cache
          composer show --locked -N > locked_modules_new.txt

      - name: Find new modules dependencies in composer lock
        id: find-new-modules-lock
        run: |
          comm -13 base/locked_modules_old.txt locked_modules_new.txt > locked_modules.txt
          if [ ! -s locked_modules.txt ]; then
            echo "No new modules in composer lock."
          else
            echo "⚠️ New modules in composer lock:"
            cat locked_modules.txt
            echo "new_locked_modules=true" >> ${GITHUB_OUTPUT}
          fi

      - name: New modules review comment to PR
        id: module-lock-comment-pr
        if: ${{ steps.find-new-modules-lock.outputs.new_locked_modules == 'true' }}
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          MODULES=$(awk '{printf "[%s] ", $0}' locked_modules.txt | sed 's/ $//')
          printf "composer.lock: New modules in lock: %s\n" "$MODULES" \
          | reviewdog -efm="%f: %m" \
            -name="COMPOSER LOCK MODULES" \
            -reporter=github-pr-review \
            -filter-mode=nofilter \
            -level=warning

      - name: Run composer outdated and post with reviewdog
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          composer outdated --direct --format=json | \
          jq -r '.installed[] | select(.version != .latest) | 
          "composer.json:1:📦 **\(.name)**  
          `\(.version)` → `\(.latest)`  
          💡 _Status: \(if .latest_status == "null" then "update available" else .latest_status end)_  
          [More info](\(.homepage))"' \
          | reviewdog -f=rdjsonl \
          -name="COMPOSER OUTDATED" \
          -reporter=github-pr-review \
          -level=info \
          -filter-mode=nofilter

      - name: Enable newly installed modules
        id: module-enable
        if: ${{ steps.find-new-modules.outputs.new_modules == 'true' }}
        run: |
          bin/magento module:enable --all -n --no-ansi -q 2>/dev/null || true

      - name: Run setup di compile
        id: setup-di-compile
        if: ${{ steps.find-new-modules.outputs.new_modules == 'true' }}
        run: | 
          bin/magento setup:di:compile -n
      
      - name: Check for lock file changes
        id: git-diff-composer-lock
        if: ${{ steps.find-new-modules.outputs.new_modules == 'true' }}
        run: |
          echo "lock_changed=$(git diff --quiet composer.lock && echo false || echo true)" >> "${GITHUB_OUTPUT}"

      - name: Check for config.php changes
        id: git-diff-config
        if: ${{ steps.find-new-modules.outputs.new_modules == 'true' }}
        run: |
          echo "config_changed=$(git diff --quiet app/etc/config.php && echo false || echo true)" >> "${GITHUB_OUTPUT}"

      - name: Commit updated config.php back to PR branch
        id: config-commit
        if: ${{ steps.git-diff-config.outputs.config_changed == 'true' }}
        uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0 #v6.0.1
        with:
          commit_message: "chore(config): Update app/etc/config.php after module enable"
          file_pattern: app/etc/config.php

      - name: Commit updated composer.lock back to PR branch
        id: composer-lock-commit
        if: ${{ steps.git-diff-composer-lock.outputs.lock_changed == 'true' }}
        uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0 #v6.0.1
        with:
          commit_message: "chore(composer): Update composer.lock to match composer.json"
          file_pattern: composer.lock
