name: PR labeler

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
      issues: write
    name: PR labeler
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
