name: PR labeler

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  labeler:
    if: >
      !contains(github.event.pull_request.labels.*.name, 'autorelease: pending') &&
      !contains(github.event.pull_request.title, 'alpha')
    permissions:
      contents: read
      pull-requests: write
      issues: write
    name: PR labeler
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 #v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
