name: Magenx CI/CD - Release PR and Build
on:
  push:
    branches:
      - main
      - staging
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '.github/**'

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:    
    - name: Release
      id: release
      uses: googleapis/release-please-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        target-branch: ${{ github.ref_name }}
        release-type: simple
        manifest-file: .release-please-manifest.json
        config-file: .release-please-config.json

    - name: Release validation
      id: release_validation
      if: ${{ !steps.release.outputs.release_created }}
      run: |
        echo "No release was created."
        echo "Release PR created: ${{ steps.release.outputs.prs_created }}"
        echo "Stopping workflow."
        exit 1        

    - name: Release created - show tag
      id: tag_name
      run: |
        echo "Tag created: ${{ steps.release.outputs.tag_name }}"
        
    - name: Checkout latest tag ${{ steps.release.outputs.tag_name }}
      id: checkout_latest_tag
      uses: actions/checkout@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        ref: ${{ steps.release.outputs.tag_name }}
        fetch-depth: 0
        persist-credentials: false
        
    - name: Github Actions workflow identification
      id: github_user
      run: |
         git config --global user.name "Magenx CI/CD"
         git config --global user.email "admin@magenx.com"

    - name: Composer install modules and updates
      id: composer_install
      env:
        COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
      run: |
        composer install --no-dev --no-cache --no-interaction  --optimize-autoloader --apcu-autoloader

    - name: Run setup di compile
      id: setup_di_compile
      run: bin/magento setup:di:compile -n

    - name: Generate static files
      id: generate_static_content
      run: bin/magento setup:static-content:deploy -f -n

    - name: Debug with custom output
      id: debug
      run: bin/magento

    - name: Set version for complete build
      id: set_build_version
      run: | 
        echo "BUILD_FILE=build_${{ github.ref_name }}_${{ steps.release.outputs.tag_name }}_$(date +%Y%m%d_%H%M).tar.gz" >> ${GITHUB_ENV}

    - name: Package build into tar archive
      id: build_tar_archive
      run: | 
        tar --ignore-failed-read --warning=no-file-changed \
          -czf "${{ env.BUILD_FILE }}" \
          --exclude=".git" \
          --exclude=".github" \
          --exclude="app/etc/env.php" \
          --exclude="CHANGELOG.md" \
          --exclude=".release*" \
          --exclude="${{ env.BUILD_FILE }}" \
          .

    - name: Attach build archive
      id: attach_build_archive
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: ${{ env.BUILD_FILE }}
        tag_name: ${{ steps.release.outputs.tag_name }}

