name: Magenx CI/CD

on:
  push:
    branches: 
      - main
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '.github/**.yml'

permissions:
  contents: write
  issues: write
  pull-requests: write
  repository-projects: read
  actions: read
  
env:
  PRERELEASE_TYPE: "alpha"
  PRERELEASE_CONFIG: ".github/.release-please-config-prerelease.json"
  PRERELEASE_MANIFEST: ".github/.release-please-manifest-prerelease.json"
  RELEASE_CONFIG: ".github/.release-please-config.json"
  RELEASE_MANIFEST: ".github/.release-please-manifest.json"

concurrency:
  group: release

jobs:

  pre-release-pr:
    name: Create pre-release PR
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: Create pre-release
        id: release
        uses: googleapis/release-please-action@v4.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: ${{ env.PRERELEASE_CONFIG }}
          manifest-file: ${{ env.PRERELEASE_MANIFEST }}

  pre-release-validate:
    if: ${{ needs.pre-release-pr.outputs.releases_created == 'false' }}
    needs: pre-release-pr
    uses: ./.github/workflows/_build.yml
    secrets:
      COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
          
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    environment: staging
    needs: pre-release-validate
    steps:
      - name: Atomic deployment
        run: |
          echo "Deploying to staging!"

  pre-release:
    name: Publish pre-release then release PR
    runs-on: ubuntu-latest
    if: ${{ needs.pre-release-pr.outputs.releases_created == 'true' && contains(needs.pre-release-pr.outputs.tag_name, 'alpha') }}
    needs: pre-release-pr
    steps:
      - name: Pre-release publishing
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr=$(gh pr list \
            --repo "$GITHUB_REPOSITORY" \
            --state merged \
            --label "autorelease: tagged" \
            --search "alpha in:title" \
            --json number \
            --limit 1 \
            --jq '.[0].number')
          echo "pr_number=$pr" >> ${GITHUB_OUTPUT}

      - name: Find artifact id
        id: extract-artifact-id
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          comments=$(gh pr view ${{ github.event.pull_request.number }} --repo "$GITHUB_REPOSITORY" --json comments --jq '.comments')
          artifact_id=$(echo "$comments" | jq -r '.[] | select(.body | test("READY TO DEPLOY")) | .body' | \
          grep -oP 'READY TO DEPLOY: \K[0-9]+' | tail -n1)
          echo "artifact_id=$artifact_id" >> ${GITHUB_OUTPUT}

      - name: Find artifact id
        id: download-artifact
        uses: actions/download-artifact@v4
        with:
          artifact-ids: ${{ steps.extract-artifact-id.outputs.artifact_id }}

      - name: Attach build archive
        id: attach_build_archive
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: "${{ steps.download-artifact.outputs.download-path }}/*"
          tag_name: ${{ needs.pre-release-pr.outputs.tag_name }}

      - name: Create release PR
        if: ${{ always() }}
        uses: googleapis/release-please-action@v4.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: ${{ env.RELEASE_CONFIG }}
          manifest-file: ${{ env.RELEASE_MANIFEST }}
          


  after-pre-release:
    name: After pre-release cleanup
    runs-on: ubuntu-latest
    needs: pre-release
    steps:
      - name: After pre-release cleanup
        run: |
          echo "Running after-pre-release cleanup"


  release:
    name: Create Release
    runs-on: ubuntu-latest
    if: ${{ needs.pre-release-pr.outputs.releases_created == 'true' && !contains(needs.pre-release-pr.outputs.tag_name, 'alpha') }}
    needs: pre-release-pr
    steps:
      - name: Create release
        run: |
          echo "Create release"


  after-release:
    name: After release cleanup
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: After release cleanup
        run: |
          echo "After release cleanup"
