name: Create Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**/*.php'
      - '**/*.xml'
      - '**/*.phtml'
      - 'app/design/**'
      - 'app/code/**'
      - 'app/etc/**'
      - 'composer.json'
      - 'composer.lock'

permissions:
  contents: write
  issues: write
  pull-requests: write
  repository-projects: read

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:       
#    - name: Create release and attach build archive
#      id: create_release
#      uses: cycjimmy/semantic-release-action@v4
#      env:
#        GITHUB_TOKEN: ${{ secrets.CI_DEMO_GITHUB_TOKEN }}
#      with:
#        semantic_version: 19.0.5
#        extra_plugins: |
#          @semantic-release/changelog
#          @semantic-release/git
#          conventional-changelog-conventionalcommits

    - name: Create release
      id: release
      uses: googleapis/release-please-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        release-type: simple
