name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**/*.php'
      - '**/*.xml'
      - '**/*.phtml'
      - 'app/design/**'
      - 'app/code/**'
      - 'app/etc/**'
      - 'composer.json'
      - 'composer.lock'

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
