name: "Magento compilation"

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - app/code/**
      - app/etc/di.xml

jobs:
  compile:
    if: "${{ ! startsWith(github.head_ref, 'release-please') || ! contains(github.event.pull_request.labels.*.name, 'autorelease: pending') }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest tag
        id: checkout-latest-tag
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Configure Composer cache
        id: composer-cache
        uses: ./.github/actions/composer-cache

      - name: Magento compilation setup:di:compile
        id: setup-di-compile
        uses: ./.github/actions/setup-di-compile
        with:
          composer_install: true
          composer_auth: "${{ secrets.COMPOSER_AUTH }}"
          composer_options: ""
          setup_compile_options: ""
          static_content_deploy: ""
          static_content_deploy_options: ""
          debug_command: "bin/magento"

