name: "ZAP Security Scan"

on:
  workflow_run:
    workflows: ["Deploy to environment"]
    types: [completed]

jobs:
  zap_scan:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
        ### for extended configuration files
      - name: Checkout latest tag
        id: checkout-latest-tag
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

      - name: ZAP Scan
        uses: zaproxy/action-baseline@de8ad967d3548d44ef623df22cf95c3b0baf8b25 #v0.15.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: ${{ secrets.WEBSITE_URL }}
          issue_title: "ZAP Scan Baseline Report"
          cmd_options: "-l WARN -D 1 -a -s -j"
